"""Export a distilled student MLP as a PROGMEM C header for the Arduino Nano.

Reads the .pt produced by distill.py and writes a self-contained header at
RotaryInvertedPendulum-arduino/RLControl/policy_weights.h. The Arduino
sketch reads weights with `pgm_read_float()` so they live in flash, not
SRAM.

Usage:
    python export_weights.py \\
        --student runs/async_35hz_v2_extend/distill_h32_aug/student.pt \\
        --header  ../../../RotaryInvertedPendulum-arduino/RLControl/policy_weights.h
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np
import torch

from distill import StudentMLP


def _format_array_2d(name: str, arr: np.ndarray) -> str:
    rows, cols = arr.shape
    lines = [f"const float {name}[{rows}][{cols}] PROGMEM = {{"]
    for r in range(rows):
        vals = ", ".join(f"{float(v):+.8e}f" for v in arr[r])
        lines.append(f"    {{ {vals} }}{',' if r < rows - 1 else ''}")
    lines.append("};")
    return "\n".join(lines)


def _format_array_1d(name: str, arr: np.ndarray) -> str:
    n = arr.shape[0]
    vals = ",\n    ".join(f"{float(v):+.8e}f" for v in arr)
    return f"const float {name}[{n}] PROGMEM = {{\n    {vals}\n}};"


def export(student_path: Path, header_path: Path, *, source_name: str | None = None) -> dict:
    ckpt = torch.load(str(student_path), map_location="cpu", weights_only=True)
    hidden = int(ckpt["hidden"])
    obs_dim = int(ckpt["obs_dim"])
    act_dim = int(ckpt["act_dim"])
    val_mse = float(ckpt.get("val_mse", float("nan")))

    model = StudentMLP(hidden=hidden, obs_dim=obs_dim, act_dim=act_dim)
    model.load_state_dict(ckpt["state_dict"])
    sd = model.state_dict()

    W1 = sd["fc1.weight"].cpu().numpy().astype(np.float32)  # (H, 5)
    B1 = sd["fc1.bias"].cpu().numpy().astype(np.float32)    # (H,)
    W2 = sd["fc2.weight"].cpu().numpy().astype(np.float32)  # (H, H)
    B2 = sd["fc2.bias"].cpu().numpy().astype(np.float32)    # (H,)
    W3 = sd["fc3.weight"].cpu().numpy().astype(np.float32)  # (1, H)
    B3 = sd["fc3.bias"].cpu().numpy().astype(np.float32)    # (1,)

    n_params = sum(a.size for a in (W1, B1, W2, B2, W3, B3))
    flash_bytes = n_params * 4

    header = []
    header.append("// auto-generated by export_weights.py — do not edit by hand")
    if source_name:
        header.append(f"// source: {source_name}")
    header.append(f"// generated: {dt.datetime.now().isoformat(timespec='seconds')}")
    header.append(f"// student MLP: {obs_dim} -> {hidden} -> {hidden} -> {act_dim}")
    header.append(f"// params: {n_params}, flash bytes: {flash_bytes}")
    header.append(f"// distill val_mse: {val_mse:.6f}")
    header.append("#pragma once")
    header.append("#include <avr/pgmspace.h>")
    header.append("")
    header.append(f"#define POLICY_OBS_DIM     {obs_dim}")
    header.append(f"#define POLICY_HIDDEN_DIM  {hidden}")
    header.append(f"#define POLICY_OUT_DIM     {act_dim}")
    header.append("")
    header.append(_format_array_2d("POLICY_W1", W1))
    header.append(_format_array_1d("POLICY_B1", B1))
    header.append(_format_array_2d("POLICY_W2", W2))
    header.append(_format_array_1d("POLICY_B2", B2))
    header.append(_format_array_2d("POLICY_W3", W3))
    header.append(_format_array_1d("POLICY_B3", B3))
    header.append("")

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(header))
    print(f"wrote {header_path}")
    print(f"  {obs_dim}->{hidden}->{hidden}->{act_dim}, "
          f"{n_params} params, {flash_bytes} bytes flash, "
          f"val_mse={val_mse:.6f}")
    return {
        "hidden": hidden,
        "obs_dim": obs_dim,
        "act_dim": act_dim,
        "n_params": n_params,
        "flash_bytes": flash_bytes,
        "val_mse": val_mse,
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Export a student MLP as a PROGMEM C header")
    p.add_argument("--student", required=True, type=Path,
                   help="path to a student.pt produced by distill.py")
    p.add_argument("--header", required=True, type=Path,
                   help="output path for the generated .h (e.g. policy_weights.h)")
    p.add_argument("--source-name", default=None,
                   help="comment string identifying the source run (e.g. distill_h32_aug)")
    args = p.parse_args(argv if argv is not None else sys.argv[1:])
    export(args.student, args.header, source_name=args.source_name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
