// Auto-generated by gen_firmware_version.py — do not edit by hand.
// Hashes LowLevelServer.ino + StepperUtils.h; CMD_GET_FIRMWARE_VERSION
// reports this value so a host can tell a stale/wrong sketch apart
// from a byte-for-byte match without reflashing.
#define FIRMWARE_VERSION_HASH 0x7AACB3B7UL
