"""Regenerate firmware_version.h from this sketch's own source.

CMD_GET_FIRMWARE_VERSION (see LowLevelServer.ino) reports the value this
script computes, baked in at compile time. tools/pi_demo/flash_if_needed.py
runs this same script against its local checkout before deciding whether a
Pi needs to actually reflash the Nano, or whether the board already has the
exact sketch running.

Usage:
    python gen_firmware_version.py
"""

from __future__ import annotations

import hashlib
from pathlib import Path

SKETCH_DIR = Path(__file__).resolve().parent

# Every file that affects the compiled sketch's behavior. Add to this list
# if LowLevelServer.ino grows another local #include.
SOURCES = ["LowLevelServer.ino", "StepperUtils.h"]

OUTPUT = SKETCH_DIR / "firmware_version.h"


def compute_hash() -> int:
    h = hashlib.sha256()
    for name in SOURCES:
        h.update((SKETCH_DIR / name).read_bytes())
    # Truncated to 4 bytes: plenty to distinguish source revisions, and it
    # matches a single uint32_t on the wire (see CMD_GET_FIRMWARE_VERSION).
    return int.from_bytes(h.digest()[:4], "little")


def main() -> None:
    version = compute_hash()
    OUTPUT.write_text(
        "// Auto-generated by gen_firmware_version.py — do not edit by hand.\n"
        "// Hashes LowLevelServer.ino + StepperUtils.h; CMD_GET_FIRMWARE_VERSION\n"
        "// reports this value so a host can tell a stale/wrong sketch apart\n"
        "// from a byte-for-byte match without reflashing.\n"
        f"#define FIRMWARE_VERSION_HASH 0x{version:08X}UL\n"
    )
    print(f"firmware_version.h -> 0x{version:08X}")


if __name__ == "__main__":
    main()
